package com.nattguld.identity.person.profile;

import com.nattguld.util.maths.Maths;
import com.nattguld.util.text.TextUtil;

/**
 * 
 * @author randqm
 *
 */

public class BioHandler {
	
	/**
	 * The available bio's.
	 */
	public static final String[] BIOS = new String[] {
			"The best things come from living outside of your comfort zone",
			"Here's my story for the history books",
			"I'm a cupcake in search for her stud muffin",
			"In a world where you can be anyone, be yourself",
			"Success is in my veins",
			"Yup, I'm just another Instagram influencer",
			"Scratch here ▒▒▒▒▒▒▒▒▒▒ to unveil my secret bio.",
			"No this isn't a dream, this is my reality",
			"What should I put here?",
			"Welcome to my world",
			"Simplicity is the key to happiness",
			"If I was a writer I'd have a better Instagram bio quote",
			"You can't become the best without first being the worst",
			"In a world of worriers, be the warrior",
			"It won't always be easy, but always try to do what's right",
			"She turned her cant's into cans and her dreams into plans",
			"Life is what happens to you while you scroll through Instagram",
			"A day in the life of me: Eat avocado toast, post Instagram videos, read Instagram comments",
			"It's my time to step into the spotlight, I've earned it",
			"I practice what I post",
			"Dreams 👉 Goals",
			"If love is in the air” why is the air so polluted?",
			"It took me {18|19|20|21|22|23|24} years to look like this",
			"Currently saying yes to new adventures",
			"I'm hurt but I still smile. That's my life.",
			"Midnight snacker 🌝",
			"Everyone else was taken so this is me",
			"Recovering cake addict 🎂",
			"I make money in my sleep 🛌",
			"People call me Sara but you can call me tonight 😉",
			"Welcome to my 👑dom",
			"Traveller ✈️ Book Lover 📖 Obsessed with tacos 🌮",
			"Currently hanging out in 🇵🇹",
			"❤️ Lover not a fighter spreading ✌️all over the 🌎",
			"Leaving a bit of sparkle everywhere I go ✨",
			"I believe in making the impossible possible because there's no fun in giving up",
			"Turned my dreams into my vision and my vision into my reality",
			"Smart. Strong. Silly. Straight up class act.",
			"I'm not perfect but stories are always better with a touch of imperfection",
			"My standards are high… just like my heels",
			"Me: {Natural|Happy|Normal|Simple} girls are the prettiest Also me: I'd like to buy {15 pounds|some|a bunch|15kg} of makeup {please|yo}",
			"Who runs the world? {ME.|Me!|Girls!|Not me that's for sure}",
			"{Happiness|Laughing|Pleassure|Pijamas} never goes out of style",
			"I'm a woman with {ambition|a smile|humor|drive} and a heart of gold",
			"I shine from within so no one can dim my light",
			"Living life on my own terms",
			"I don't care what people think of me this is me in {rawest|my best|my real} form",
			"I'd rather be hated for who I am than {loved|worshipped} for who I am not",
			"Risk taker. Adventurer. Globetrotter. Living my dreams", //TODO
			"I might not be where I want to be yet but I get closer everyday",
			"One day, I hope to be a happily married old woman telling wild stories from her wild youth",
			"I got to where I am today by being {me|myself}",
			"I was {born|put in this world} to do exactly what I'm doing today",
			"Don't like me? Don't care.",
			"I'm out here {hustlin'|hustling|chillin} to claim what's mine",
			"Follow Me To {Greatness|Happiness|The rainbow|The horizon}",
			"Thank you, come again. ",
			"Don't know what to do? You can start by hitting that follow button.",
			"Click the follow button to be part of my {life|love|naughty|great|sparkling|happy} journey",
			"Wanna know my {story|secrets|greatness}? Press that follow button.",
			"I'm on my journey. Join me by following along.",
			"Follow me to get a {behind the scenes|true|interesting|secret|hidden} look at my life",
			"Follow along to witness {history|greatness} in the making",
			"🍂🍃Falling for you 🍂🍃",
			"☕Stressed, blessed, and coffee obsessed ☕",
			"Having the time of my life ⏰🎉",
			"Looking at the world through 🌹colored glasses",
			"I'm sweet like honey 🍯",
			"Don't study me. You won't graduate 🎓",
			"🌟Sending my selfies to NASA because I'm a star 🌟",
			"Please cancel my subscription to your issues",
			"Status Update: Currently hungry 🍔🍟🌭🌮🥗🍪",
			"They call me Febreeze because I'm so fresh",
			"Don't kale my vibe",
			"Follow my Instagram or I'm nacho friend anymore",
			"I believe in bee-ing myself",
			"My Instagram account is very a-peel-ing",
			"Seas the day",
			"I like to stop and smell the rosé",
			"I'm pawsome and currently having a purrfect day",
			"Spending my days in a well so I can say they've been well spent",
			"Artists never retire, they withdraw instead",
			"I've been told ‘You are what you eat.' Guess I ate a sexy beast this morning.",
			"My name ain't Mary but I'm still poppin'",
			"I'm the exception",
			"Simple but significant",
			"Rollin' with the homies",
			"Livin' a little",
			"Pretty & Profitable",
			"Life is beautiful",
			"Glitter is the only option",
			"Anything but predictable",
			"I see beauty in everything",
			"Goal: bigger smile",
			"I apologize for anything I post while hungry",
			"Humble, with just a hint of Kanye",
			"I'd rather steal your dessert than your boyfriend",
			"Sassy, classy with a touch of badassy",
			"One day, I hope to become a grown up",
			"Used to think I was a tad indecisive, but now I'm not quite sure",
			"Life is short so I'm smiling while I've still got all my teeth",
			"My hobbies are breakfast, lunch, and dinner topped with a chocolate dessert",
			"Relationship status: Netflix and ice cream",
			"The bags under my eyes are Chanel",
			"Instagram bio currently loading",
			"I'm actually not funny. I'm just really mean but people always think I'm joking.",
			"I'm a social media guru. No, really, I am.",
			"So many of my smiles are because of you",
			"So grateful to be sharing my world with you",
			"All your dreams can come true and I'll make sure of it",
			"Live in the sunshine where you belong",
			"My life is better than my daydreams",
			"Sprinkling kindness everywhere I go",
			"I love my followers more than life itself",
			"Don't regret the opportunities you were too afraid to take",
			"Sometimes we could always use a little magic – don't hide the magic within you",
			"Every day might not be a good day but there is good in every day",
			"Not like the rest of them",
			"Oh, you 😊",
			"One of a kind",
			"The best things in life are really expensive. You can have me for {a|2|3|4|5|6|7|8|9|10|100} billion 😉",
			"Aloha 🌴🌴🌴🌴🌴🌴",
			"Hi. Hello. Hola. Ola. Bonjour. Ciao. Guten Tag. Namaste. Salaam.",
			"Life's short, eat the cake 🍰",
			"Adding a little sparkle to your day ✨",
			"I regret nothing you see in this feed",
			"My greatest fear isn't starting. My greatest fear is not making it to the top.",
			"I believe in helping people",
			"Enjoying every second of my life, follow along and see for yourself",
			"When the pain passes, you eventually see how much good came out of a bad situation",
			"Love 💗 and Peace ✌️",
			"Mentally on the beach 🏖️",
			"If you want the tea, follow me ☕",
			"Dreaming bigger than my imagination can handle",
			"Starting over",
			"Just going with the flow 🌊",
			"I'm sparkling like my water ✨",
			"I don't come with instructions but my captions are the next best thing 📚",
			"Keepin' it real since {1998|1999|2000|2001|2002}",
			"I'm as rare as the Reckon Expert outfit skin in Fortnite",
			"I'm a limited edition, there's only one me",
			"In 2020, I'm going to be better than I've ever been before",
			"Less talking, more action. Take a look at my pictures if you don't believe me",
			"I am worthy of the greatness I hold",
			"It's not your job to like me, it's mine.",
			"I'm awesome (don't worry I think you are too)",
			"I'm not here to be average, I'm here to be the best",
			"Born to shine bright",
			"Even if you had instructions, you still couldn't handle me",
			"Anything but predictable",
			"Be young. Be dope. Run the show.",
			"I'll remember and recover but that doesn't mean I'll forgive and forget",
			"I'd rather make mistakes than fake perfection",
			"I don't wipe tears, I wipe the people who created them",
			"I'm like coffee: dark, bitter and too hot for you",
			"In a world of average, I'm savage",
			"It's hard to find someone who's smart, funny, adorable and a total badass. My only advice for you is, don't forget to follow me",
			"Too glam to give a damn",
			"My Instagram is proof that I'm always creating a better version of myself",
			"Don't care what you say about me I like the way I am",
			"Love without limits",
			"I'm suffering from an extreme case of not being a Kardashian",
			"Together we could be unstoppable",
			"In a world of darkness look up at the stars",
			"I'm so deep even the ocean gets jealous",
			"Tell me not to do something and I'll do it twice and take pictures",
			"All i do is win, win, win. No matter what.",
			"In a world where you can have everything. Be a giver first.",
			"You become what you believe, so believe in yourself",
			"This is me",
			"Welcome to my Instagram",
			"This is my life",
			"I got nothing",
			"Screw perfect.",
			"Happy thoughts",
			"Just smiles 🙂",
			"Meet. Me.",
			"This is my bio",
			"...",
			"Single. Determined. Living life.",
			"Creating sunshine in the world",
			"I wonder how many calories my exes burned jumping to conclusions",
			"Always better together xoxo",
			"You'll never shine if all you do is throw shade",
			"Just a little bit imperfect",
			"Real queens fix each other's crowns",
			"Today's the kind of day I live for",
			"No one's life is as perfect as their Instagram feed",
			"I don't know where I'm going but I'm going",
			"Everyday I create a life I love",
			"When the world is dark look up to the stars 🌟🌟🌟🌟🌟🌟",
			"Trying to watch more sunsets than Netflix",
			"I'm ready – let's do this",
			"Be a flamingo in the flock of pigeons",
			"Making mistakes is better than faking perfection",
			"Sprinkling a bit of magic",
			"Sharing my happy thoughts",
			"Capture every moment",
			"I'm the rainbow 🌈 on the rainy day 🌧️",
			"I dress as if I'm about to see my arch nemesis",
			"My clothes might not change the world, but I sure will",
			"I'll make you stop and stare",
			"My clothes highlight my colorful life",
			"I may be a fashionista but I'm not all about labels",
			"Shopping is my therapy – hey, it's cheaper 😉",
			"I need new clothes.” – Me, every damn day",
			"My ex doesn't go with my outfit",
			"Money can't be the root of evil since shopping brings people so much happiness",
			"Women can look beautiful in any outfit but the right outfit can make women become powerful",
			"When you feel like giving up, keep going",
			"You are what you do, not what you say you'll do",
			"Strength comes from doing things you thought you couldn't",
			"Do something today that your future self will thank you for",
			"Today doesn't need your excuses. Make it happen.",
			"Shh… I'm a Victoria's Secret model. It's such a big secret, not even Victoria knows",
			"I'm not just a girl with a phone, I'm a model",
			"The prettiest smiles hide the biggest secrets",
			"I wear confidence on my sleeve",
			"The most important part of a camera is the person in front of it",
			"I take a lot of selfies for my future biographer",
			"Life is short, make every selfie count",
			"#Beyourselfie",
			"I might not know who I am but I know where I want to be. Right here in paradise.",
			"My best stories are found within the pages of my passport",
			"I haven't been there yet but it's on my list",
			"All I need is Vitamin Sea 🌊",
			"I like taking the scenic route",
			"Take advantage of every opportunity you get because some things only happen once in a lifetime",
			"Fill your life with experiences so you always have a great story to tell",
			"It's better to be a lonely lion than a popular sheep",
			"Wake. Play. Slay.",
			"Creating the life of my dreams one day at a time",
			"I've scrolled millions of miles with my thumbs",
			"Life isn't perfect but your photos can be",
			"C'est la vie",
			"I strive to impress myself",
			"See the good in the world",
			"Single and {lonely|searching|looking|looking for love|ready to mingle}",
			"I may be a handful but hey you've got two hands!",
			"Whatever is good for your soul, do that",
			"Even the stars were jealous of the sparkle in her eyes",
			"Stress less and enjoy the best",
			"Get out there and live a little",
			"I'm not high maintenance, you're just low effort",
			"I'm not gonna sugar coat the truth, I'm not Willy Wonka",
			"Life is better when you're laughing",
			"Look for the magic in every moment",
			"Vodka may not be the answer but it's worth a shot",
			"A sass a day keeps the basics away",
			"Me, myself and I",
			"Just me",
			"But first, let me take a selfie",
			"Typical me",
			"Me doing me",
			"I was born to shine",
			"I don't always take a selfie, but when I do…",
			"I woke up like this",
			"Couldn't be happier 🙂",
			"You can regret a lot of things but you'll never regret being kind",
			"Do whatever makes you happiest",
			"Having the dream is easy, making it come true is hard” – Serena Williams",
			"Decluttering my life like Marie Kondo",
			"If I were rich, I'd pull a Netflix and spend $100 million on my Friends",
			"In 2020, I want to be as Insta famous as an egg and as ageless as Paul Rudd",
			"Can't hear, can't speak, can't see.",
			"Be heroes of your own stories” – Constance Wu",
			"Hella fine and it works every time” – Ariana Grande",
			"My life is as crooked as Rami Malek's bowtie",
			"We did it!",
			"Work hard then work harder",
			"Hustlin'",
			"When daydreams become reality",
			"Say yes, take risks, and live life on your own terms",
			"The impossible is now possible",
			"Perseverance pays… a lot!",
			"It wasn't always easy but it's worth it",
			"Pursue your passion and you'll never work a day in your life",
			"Friends are like stars, constantly coming and going, but the ones that stay burn as bright as the sun",
			"A good friend might know your wild stories but your best friend was right there with you",
			"I would never let my best friend do anything stupid…alone",
			"Hold onto your best friend because you'll never find someone like them again",
			"Find someone who brings out the best in you",
			"How can I help you?",
			"If you could be doing anything right now, what would it be?",
			"How are you guys doing?",
			"Miss me?",
			"What time is it?",
			"Don't trust everything you see, even salt can look like sugar",
			"Everyone has a chapter they don't read out loud",
			"Too lit to quit",
			"Shoutout to myself because I'm lit",
			"I don't tell you I love you out of habit but as a reminder of how much you mean to me",
			"When I started counting my blessings, I realized I have everything I could ever need",
			"A smile can change the world",
			"The biggest mistake you can ever make is to be afraid to make mistakes",
			"Life is tough but so am I",
			"My coach said I run like a girl. So I said if he ran a little faster he could too.” – Mia Hamm",
			"Oops is always better than what if",
			"If you want opportunity to knock, it's time to build a door",
			"The little things in life matter",
			"If you don't believe in yourself, who will?",
			"I may not be there yet, but I'm closer than I was yesterday",
			"It always seems impossible until it's done",
			"It may be stormy now but it never rains forever",
			"There's a dream that I've been chasing want so badly for it to be reality” – Justin Bieber",
			"Dreams don't have expiration dates, keep going.",
			"Set goals you don't tell anyone about. Achieve them. Then give yourself the highest of fives!",
			"Me",
			"Love",
			"Ugh…",
			"OMG!",
			"Surprise!",
			"Feelin' hot, hot, hot",
			"Sea, Sun and Smiles 🙂",
			"Summer lovin' happened so fast",
			"Chasin' the sun",
			"Blue skies, high tides and good vibes",
			"Hello sunshine!",
			"Life's a beach",
			"Eat, tan, sleep, repeat",
			"Act like you own the world because you do",
			"As long as my bank account keeps growing, I couldn't care less about anything else",
			"I keep it real because I'm not afraid of having enemies",
			"…um ok",
			"You were my cup of tea but I drink wine now",
			"Ambition on fleek",
			"I wouldn't chase you because I'm the catch",
			"Know your worth but don't forget to add tax",
			"I'm the reason why I smile everyday",
			"I don't care if you approve of me, I approve of myself",
			"Drop it like it's hot”",
			"Only God Can Judge Me",
			"I'm feelin' myself”",
			"To live doesn't mean you're alive”",
			"Knock me down 10 times but I get up 10”",
			"I'm the rose that came from concrete.”",
			"I'm living my best life”",
			"Looking like a right swipe on Tinder.”",
			"If you could travel anywhere in the world, where would you go first?",
			"Leavin' on a jet plane",
			"Guess where I am",
			"Work. Save. Travel. Repeat.",
			"Time for an adventure!",
			"Be right back, exploring the world",
			"Vacation calories don't count",
			"Memories made together, last forever",
			"Life is better with the sand between your toes",
			"The only vacation you'll ever regret is the one you don't take",
			"Go to the place where you feel most alive",
			"A walk in the woods feels like home",
			"By getting lost in nature, you get closer to finding yourself",
			"If you're looking for heaven on earth step outside",
			"Sometimes all the soul needs is a walk in nature",
			"If you have a garden and a library, you have everything you need",
			"Life is short and the world is wide so get out there and explore it",
			"Wherever you go, leave a trail",
			"Life is the biggest party you'll ever be at",
			"An apple a day will keep anyone away if you throw it hard enough",
			"Give second chances but not for the same mistake",
			"Never sacrifice three things: family, love, and or yourself",
			"I'm an original and that's perfection in itself",
			"You can't dull my sparkle ✨",
			"Be the person you needed when you were young",
			"Life is about taking chances and having fun",
			"So grateful for this moment",
			"I'm thankful for the struggles that made me the person I am today",
			"Messy bun and having fun",
			"I got it from my mama",
			"A great girl is classy not trashy",
			"Girls are changing the world",
			"Who run the world? GIRLS.",
			"Just like my eyeliner, I always wing it",
			"I'm not one in a million, I'm one in 7 billion",
			"Leave a little sparkle everywhere you go",
			"I'm wild and free",
			"The only person I dress to impress is me",
			"Good food, good mood",
			"I'm on a seafood diet. I see food I eat it",
			"Never settle for just one scoop",
			"Don't be upsetti, eat some spaghetti",
			"Chocolate is cheaper than therapy",
			"Waffles are just pancakes with abs",
			"Food before dudes",
			"When you're downie eat a brownie",
			"Pasta la vista baby",
			"You can't live a full life on an empty stomach",
			"Resting coffee face",
			"Hocus pocus I need coffee to focus",
			"Life is better with a coffee in hand",
			"I like big cups and I cannot lie",
			"Taking a little coffee break",
			"Feeling depresso without my espresso",
			"I like myself how I like my coffee: dark, bitter, and too hot for you",
			"Caffeine Queen",
			"Too much Monday not enough coffee",
			"When things go wrong, coffee helps",
			"Oh hey there!",
			"Short and sweet",
			"Just livin' life",
			"Just chillin'",
			"Today's perfect",
			"Why so serious?",
			"Time for a change",
			"I'd rather be someone's Sunday morning, not Saturday night",
			"Be the EXTRA in extraordinary",
			"I've got hustle and heart",
			"I don't believe in SOMEDAY, I believe in TODAY",
			"When life gives me lemons, I make lemonade then sell it",
			"My life my rules",
			"I'm not lucky, I'm talented",
			"You can beat me down but I'll just jump back up",
			"I may be down to earth but I'm still above you",
			"I'm confident, your opinion of me won't change that",
			"I could build a castle out of all the bricks they threw at me”",
			"I think I'm ready for my close up”",
			"Pictures of last night ended up online, I'm screwed”",
			"I'll just keep on living, the way I want to live”",
			"I got sinning on my mind”",
			"Find me where the wild things are”",
			"I got one less problem without ya”",
			"I'm bringing sexy back”",
			"We're always undercover”",
			"There's no way I could be stopped, was coming for your spot”",
			"Hello, it's me”",
			"Don't be average, be savage",
			"It's not my fault truth hurts, here's a bandaid",
			"Be the kind of person that makes others step up their game",
			"Single as a dollar but not looking for change",
			"Well behaved people don't make it into history books",
			"Looks aren't everything but I have them just in case",
			"People say I act like I don't care but it's not an act",
			"I can easily tell how intelligent someone is by how stupid they think I am.",
			"I'm classy, sassy and a bit badassy",
			"I've got my sassy pants on. Watch out world!",
			"I'm too glam to give a damn",
			"Who let the dogs out?",
			"You are pawfection",
			"Be the kind of person your dog thinks you are",
			"My dog thinks I'm kind of a big deal",
			"She's purrfect",
			"Fur real though",
			"I've been feline good today",
			"When I feel like giving up on my dreams, I keep sleeping",
			"The best workout is a cross between a lunge and a crunch. Lunch.",
			"If I was funny, I'd have a better Instagram caption for this",
			"*insert funny Instagram caption here*",
			"This is my pretty hungry face",
			"Namast'ay in bed",
			"Putting the ‘we' in weird",
			"We're all born a little crazy, some of us just choose to stay that way",
			"Mirror: you look amazing today Camera: Nope, you don't",
			"But first, let me take 40 selfies until choosing one that actually works",
			"You're like a four-leaf clover: hard to find and lucky to have",
			"Nothing shines brighter than a heart of gold",
			"Mistakes are proof that you've tried",
			"The journey is always the best part",
			"Today's the best kind of day",
			"Life is only as legendary as you make it",
			"Good vibes only",
			"Livin' the good life",
			"Don't judge someone by their mistakes but on how they fix them",
			"If I don't post a picture, did it even really happen?",
			"You know you've made it when your idols become your rivals",
			"They call me ranch ‘cuz I be dressing",
			"One does not simply create a clever Instagram caption",
			"Maybe she's born with it, maybe it's the Clarendon filter",
			"If the world was created in 7 days but it took 9 months to make me, I'm clearly a big deal",
			"People will judge everything you do, so you do you",
			"I just rolled my eyes so hard I saw my brain",
			"You never realize how boring your life is until someone asks you what you do for fun",
			"Be the type of person you want to meet",
			"Go BIG or go home",
			"Treat yourself like a Queen and you'll attract your King",
			"Express gratitude. Regret nothing.",
			"Motivation Monday? I'm motivated seven days a week",
			"Taco Tuesday is my favorite day of the week",
			"It's Wednesday so here's my wise quote of the day… actually I got nothing.",
			"Friday, my second favorite F word",
			"Friday, Friday, gotta get down on Friday”",
			"This is me in all my glory",
			"Keep your chin up so your crown doesn't slip",
			"Be kind. Be love.",
			"Follow your heart in everything you do",
			"Don't live a life regretting the things you didn't do. Go do things!",
			"Don't wait for the storm to pass, go out there and dance in the rain",
			"Normal is boring",
			"Be a little more you, and a lot less them.”",
			"You can't live an EPIC life without EPIC people",
			"Creating a life I love ❤️",
			"…breathe…",
			"I'm just a girl standing in front of a camera asking if this is Instagram worthy?",
			"Filling my mind with happy thoughts",
			"A coffee can't solve everything but it can solve a lot",
			"My life isn't perfect but it's the best thing that's ever happened to me",
			"Isn't it beautiful outside?",
			"Just your average Monday morning commute",
			"It's a chill in bed kinda day",
			"Sleep like no one's watching",
			"Life is a practice. You are what you do each day.",
			"Let's get the party started!",
			"Life is all about smiles and high fives",
			"Just vibes",
			"When the sun goes down, that's when you see me glow",
			"If good things come to those who wait, I'm gonna be an hour late to our date",
			"It's good that you have two hands because I can be a handful",
			"Every heart has a story waiting to be told",
	};
	
	/**
	 * Retrieves a random bio.
	 * 
	 * @return The bio.
	 */
	public static String getRandomBio() {
		String bio = BIOS[Maths.random(BIOS.length)];
		return TextUtil.spintax(bio);
	}

}
